UOM_DICT = {
    "MU":"1000 UNITS",
    "A":"ACRE",
    "ARR":"ARRAY",
    "A02":"ARRAY 02UP",
    "A03":"ARRAY 03UP",
    "A04":"ARRAY 04UP",
    "A05":"ARRAY 05UP",
    "A06":"ARRAY 06UP",
    "A07":"ARRAY 07UP",
    "A08":"ARRAY 08UP",
    "A09":"ARRAY 09UP",
    "B02":"ARRAY 102 UP",
    "B08":"ARRAY 108UP",
    "A10":"ARRAY 10UP",
    "A11":"ARRAY 11UP",
    "B20":"ARRAY 120 UP",
    "A12":"ARRAY 12UP",
    "A13":"ARRAY 13UP",
    "A14":"ARRAY 14UP",
    "B54":"ARRAY 154 UP",
    "A15":"ARRAY 15UP",
    "A16":"ARRAY 16UP",
    "A17":"ARRAY 17UP",
    "A18":"ARRAY 18UP",
    "A19":"ARRAY 19UP",
    "A20":"ARRAY 20UP",
    "A21":"ARRAY 21UP",
    "A22":"ARRAY 22UP",
    "A23":"ARRAY 23UP",
    "C47":"ARRAY 247 UP",
    "A24":"ARRAY 24UP",
    "A25":"ARRAY 25UP",
    "A26":"ARRAY 26UP",
    "A27":"ARRAY 27UP",
    "A28":"ARRAY 28UP",
    "A29":"ARRAY 29UP",
    "A30":"ARRAY 30UP",
    "A31":"ARRAY 31UP",
    "A32":"ARRAY 32UP",
    "A33":"ARRAY 33UP",
    "A34":"ARRAY 34UP",
    "A35":"ARRAY 35UP",
    "A36":"ARRAY 36UP",
    "A37":"ARRAY 37UP",
    "A38":"ARRAY 38UP",
    "A39":"ARRAY 39UP",
    "A40":"ARRAY 40UP",
    "A41":"ARRAY 41UP",
    "A42":"ARRAY 42UP",
    "A43":"ARRAY 43UP",
    "A44":"ARRAY 44UP",
    "A45":"ARRAY 45UP",
    "A46":"ARRAY 46UP",
    "A47":"ARRAY 47UP",
    "A48":"ARRAY 48UP",
    "A49":"ARRAY 49UP",
    "A50":"ARRAY 50UP",
    "A51":"ARRAY 51UP",
    "A52":"ARRAY 52UP",
    "A53":"ARRAY 53UP",
    "A54":"ARRAY 54UP",
    "A55":"ARRAY 55UP",
    "A56":"ARRAY 56UP",
    "A57":"ARRAY 57UP",
    "A58":"ARRAY 58UP",
    "A59":"ARRAY 59UP",
    "A60":"ARRAY 60UP",
    "A61":"ARRAY 61UP",
    "A62":"ARRAY 62UP",
    "A63":"ARRAY 63UP",
    "A64":"ARRAY 64UP",
    "A65":"ARRAY 65UP",
    "A66":"ARRAY 66UP",
    "A67":"ARRAY 67UP",
    "A68":"ARRAY 68UP",
    "A69":"ARRAY 69UP",
    "A70":"ARRAY 70UP",
    "A71":"ARRAY 71UP",
    "A72":"ARRAY 72UP",
    "A73":"ARRAY 73UP",
    "A74":"ARRAY 74UP",
    "A75":"ARRAY 75UP",
    "A76":"ARRAY 76UP",
    "A77":"ARRAY 77UP",
    "A78":"ARRAY 78UP",
    "A79":"ARRAY 79UP",
    "A80":"ARRAY 80UP",
    "A81":"ARRAY 81UP",
    "A82":"ARRAY 82UP",
    "A83":"ARRAY 83UP",
    "A84":"ARRAY 84UP",
    "A85":"ARRAY 85UP",
    "A86":"ARRAY 86UP",
    "A87":"ARRAY 87UP",
    "A88":"ARRAY 88UP",
    "A89":"ARRAY 89UP",
    "A90":"ARRAY 90UP",
    "A91":"ARRAY 91UP",
    "A92":"ARRAY 92UP",
    "A93":"ARRAY 93UP",
    "A94":"ARRAY 94UP",
    "A95":"ARRAY 95UP",
    "A96":"ARRAY 96UP",
    "A97":"ARRAY 97UP",
    "A98":"ARRAY 98UP",
    "A99":"ARRAY 99UP",
    "AR":"AS REQUIRED",
    "OZA":"AVOIRDUPOIS OUNCE",
    "BG":"BAGS",
    "BOT":"BOTTLE",
    "BT":"BOTTLE",
    "BOX":"BOX",
    "B1H":"BOX OF 100",
    "BTH":"BOX OF 1000",
    "B50":"BOX OF 50",
    "B5H":"BOX OF 500",
    "BDL":"BUNDLE",
    "CD":"CARD",
    "CS":"CASE",
    "CTS":"CENT",
    "CG":"CENTIGRAM",
    "CM":"CENTIMETER",
    "CNY":"CHINESE DOLLAR",
    "CM3":"CUBIC CENTIMETER",
    "FT3":"CUBIC FOOT",
    "IN3":"CUBIC INCH",
    "M3":"CUBIC METER",
    "YD3":"CUBIC YARD",
    "DAY":"DAY",
    "DZ":"DOZEN",
    "DR":"MULTI-GALLON CONTAINER",
    "EA":"EACH",
    "EU":"EDI UNIT OF MEASURE",
    "FT":"FOOT",
    "GAL":"GALLON",
    "G":"GRAM",
    "GRO":"GROSS",
    "HR":"HOUR",
    "HUN":"HUNDRED",
    "CW":"HUNDRED WEIGHT",
    "IN":"INCH",
    "JR":"JAR",
    "KG":"KILOGRAM",
    "KM":"KILOMETER",
    "KIT":"KIT",
    "FTL":"LINEAR FOOT",
    "L":"LITER",
    "LO":"LOT",
    "M":"METER",
    "MI":"MILE",
    "MG":"MILLIGRAM",
    "ML":"MILLILITER",
    "MM":"MILLIMETER",
    "MIN":"MINUTE",
    "MO":"MONTH",
    "AA":"ORDER IN AARAYS / SHIP AS ARRAYS",
    "CA":"ORDER IN CIRCUITS / SHIP AS ARRAYS",
    "CC":"ORDER IN CIRCUITS / SHIP AS CIRCUITS",
    "OZ":"OUNCE",
    "PK":"PACKAGE",
    "PC":"PACKET",
    "PD":"PAD",
    "PL":"MULTI-GALLON CONTAINER",
    "PR":"PAIR",
    "PN":"PANEL",
    "PT":"PINT",
    "PN1":"PN",
    "LBS":"POUND",
    "QT":"QUART",
    "RL":"ROLL",
    "SEC":"SECOND",
    "ST":"SET",
    "SHT":"SHEET",
    "CM2":"SQUARE CENTIMETER",
    "DM2":"SQUARE DECIMETER",
    "FT2":"SQUARE FOOT",
    "IN2":"SQUARE INCH",
    "KM2":"SQUARE KILOMETER",
    "M2":"SQUARE METER",
    "MI2":"SQUARE MILE",
    "YD2":"SQUARE YARD",
    "SY":"SYRINGE",
    "TBE":"TUBE",
    "K":"1000 EACH",
    "TN":"TIN",
    "TON":"TON",
    "OZT":"TROY OUNCE",
    "TUB":"TUBE",
    "TU":"TUBE",
    "USD":"US DOLLAR",
    "WK":"WEEK",
    "YD":"YARD",
    "YR":"YEAR",
    "YEN":"JAPANESE DOLLAR",
}

def get_uom(s):
    global UOM_DICT
    uom = None
    if s != None:
        if s in UOM_DICT.keys():
            uom = UOM_DICT[s]
        else:
            uom = s
    return uom